spring.application.name=TaskFlow-Backend
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging configuration
logging.level.com.taskflow=DEBUG
logging.level.com.taskflow.config.JwtAuthenticationFilter=DEBUG
logging.level.com.taskflow.controller.AuthenticationController=DEBUG
logging.level.org.springframework.security=DEBUG

# Set default profile to dev
spring.profiles.active=dev
