# Production Configuration
# DB settings should also be injected here in a real scenario

# JWT Configuration (Must be provided via env var)
application.security.jwt.secret-key=${JWT_SECRET}

# Logging
logging.level.com.taskflow=INFO
